import type { ModelPricing } from '@/types/pricing';

export const PRICING_DATA: ModelPricing[] = [
  // OpenAI — Flagship (Short + Long context)
  {
    id: 'gpt-5.4',
    provider: 'openai',
    model: 'GPT-5.4',
    inputPrice: 2.5,
    cachedInputPrice: 0.25,
    outputPrice: 15.0,
    longContextInputPrice: 5.0,
    longContextCachedInputPrice: 0.5,
    longContextOutputPrice: 22.5,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-5.4-mini',
    provider: 'openai',
    model: 'GPT-5.4 mini',
    inputPrice: 0.75,
    cachedInputPrice: 0.075,
    outputPrice: 4.5,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-5.4-nano',
    provider: 'openai',
    model: 'GPT-5.4 nano',
    inputPrice: 0.2,
    cachedInputPrice: 0.02,
    outputPrice: 1.25,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-5.4-pro',
    provider: 'openai',
    model: 'GPT-5.4 pro',
    inputPrice: 30.0,
    outputPrice: 180.0,
    longContextInputPrice: 60.0,
    longContextOutputPrice: 270.0,
    contextWindow: 1_000_000,
  },

  // OpenAI — GPT-5.x series
  {
    id: 'gpt-5.2',
    provider: 'openai',
    model: 'GPT-5.2',
    inputPrice: 1.75,
    cachedInputPrice: 0.175,
    outputPrice: 14.0,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-5.2-pro',
    provider: 'openai',
    model: 'GPT-5.2 pro',
    inputPrice: 21.0,
    outputPrice: 168.0,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-5.1',
    provider: 'openai',
    model: 'GPT-5.1',
    inputPrice: 1.25,
    cachedInputPrice: 0.125,
    outputPrice: 10.0,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-5',
    provider: 'openai',
    model: 'GPT-5',
    inputPrice: 1.25,
    cachedInputPrice: 0.125,
    outputPrice: 10.0,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-5-mini',
    provider: 'openai',
    model: 'GPT-5 mini',
    inputPrice: 0.25,
    cachedInputPrice: 0.025,
    outputPrice: 2.0,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-5-nano',
    provider: 'openai',
    model: 'GPT-5 nano',
    inputPrice: 0.05,
    cachedInputPrice: 0.005,
    outputPrice: 0.4,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-5-pro',
    provider: 'openai',
    model: 'GPT-5 pro',
    inputPrice: 15.0,
    outputPrice: 120.0,
    contextWindow: 1_000_000,
  },

  // OpenAI — GPT-4.1 series
  {
    id: 'gpt-4.1',
    provider: 'openai',
    model: 'GPT-4.1',
    inputPrice: 2.0,
    cachedInputPrice: 0.5,
    outputPrice: 8.0,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-4.1-mini',
    provider: 'openai',
    model: 'GPT-4.1 mini',
    inputPrice: 0.4,
    cachedInputPrice: 0.1,
    outputPrice: 1.6,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-4.1-nano',
    provider: 'openai',
    model: 'GPT-4.1 nano',
    inputPrice: 0.1,
    cachedInputPrice: 0.025,
    outputPrice: 0.4,
    contextWindow: 1_000_000,
  },
  {
    id: 'gpt-4o',
    provider: 'openai',
    model: 'GPT-4o',
    inputPrice: 2.5,
    cachedInputPrice: 1.25,
    outputPrice: 10.0,
    contextWindow: 128_000,
  },
  {
    id: 'gpt-4o-mini',
    provider: 'openai',
    model: 'GPT-4o mini',
    inputPrice: 0.15,
    cachedInputPrice: 0.075,
    outputPrice: 0.6,
    contextWindow: 128_000,
  },
  {
    id: 'o3',
    provider: 'openai',
    model: 'o3',
    inputPrice: 2.0,
    cachedInputPrice: 0.5,
    outputPrice: 8.0,
    contextWindow: 200_000,
  },
  {
    id: 'o3-mini',
    provider: 'openai',
    model: 'o3 mini',
    inputPrice: 1.1,
    cachedInputPrice: 0.55,
    outputPrice: 4.4,
    contextWindow: 200_000,
  },
  {
    id: 'o4-mini',
    provider: 'openai',
    model: 'o4-mini',
    inputPrice: 1.1,
    cachedInputPrice: 0.275,
    outputPrice: 4.4,
    contextWindow: 200_000,
  },
  {
    id: 'o3-pro',
    provider: 'openai',
    model: 'o3-pro',
    inputPrice: 20.0,
    outputPrice: 80.0,
    contextWindow: 200_000,
  },
  {
    id: 'o1',
    provider: 'openai',
    model: 'o1',
    inputPrice: 15.0,
    cachedInputPrice: 7.5,
    outputPrice: 60.0,
    contextWindow: 200_000,
  },
  {
    id: 'o1-mini',
    provider: 'openai',
    model: 'o1 mini',
    inputPrice: 1.1,
    cachedInputPrice: 0.55,
    outputPrice: 4.4,
    contextWindow: 128_000,
  },
  {
    id: 'o1-pro',
    provider: 'openai',
    model: 'o1-pro',
    inputPrice: 150.0,
    outputPrice: 600.0,
    contextWindow: 200_000,
  },

  // OpenAI — Legacy models
  {
    id: 'gpt-4o-2024-05-13',
    provider: 'openai',
    model: 'GPT-4o (2024-05-13)',
    inputPrice: 5.0,
    outputPrice: 15.0,
    contextWindow: 128_000,
  },
  {
    id: 'gpt-4-turbo-2024-04-09',
    provider: 'openai',
    model: 'GPT-4 Turbo (2024-04-09)',
    inputPrice: 10.0,
    outputPrice: 30.0,
    contextWindow: 128_000,
  },
  {
    id: 'gpt-4-0125-preview',
    provider: 'openai',
    model: 'GPT-4 (0125-preview)',
    inputPrice: 10.0,
    outputPrice: 30.0,
    contextWindow: 128_000,
  },
  {
    id: 'gpt-4-1106-preview',
    provider: 'openai',
    model: 'GPT-4 (1106-preview)',
    inputPrice: 10.0,
    outputPrice: 30.0,
    contextWindow: 128_000,
  },
  {
    id: 'gpt-4-1106-vision-preview',
    provider: 'openai',
    model: 'GPT-4 Vision (1106)',
    inputPrice: 10.0,
    outputPrice: 30.0,
    contextWindow: 128_000,
  },
  {
    id: 'gpt-4-0613',
    provider: 'openai',
    model: 'GPT-4 (0613)',
    inputPrice: 30.0,
    outputPrice: 60.0,
    contextWindow: 8_192,
  },
  {
    id: 'gpt-4-0314',
    provider: 'openai',
    model: 'GPT-4 (0314)',
    inputPrice: 30.0,
    outputPrice: 60.0,
    contextWindow: 8_192,
  },
  {
    id: 'gpt-4-32k',
    provider: 'openai',
    model: 'GPT-4 32K',
    inputPrice: 60.0,
    outputPrice: 120.0,
    contextWindow: 32_768,
  },
  {
    id: 'gpt-3.5-turbo',
    provider: 'openai',
    model: 'GPT-3.5 Turbo',
    inputPrice: 0.5,
    outputPrice: 1.5,
    contextWindow: 16_385,
  },
  {
    id: 'gpt-3.5-turbo-0125',
    provider: 'openai',
    model: 'GPT-3.5 Turbo (0125)',
    inputPrice: 0.5,
    outputPrice: 1.5,
    contextWindow: 16_385,
  },
  {
    id: 'gpt-3.5-turbo-1106',
    provider: 'openai',
    model: 'GPT-3.5 Turbo (1106)',
    inputPrice: 1.0,
    outputPrice: 2.0,
    contextWindow: 16_385,
  },
  {
    id: 'gpt-3.5-turbo-0613',
    provider: 'openai',
    model: 'GPT-3.5 Turbo (0613)',
    inputPrice: 1.5,
    outputPrice: 2.0,
    contextWindow: 16_385,
  },
  {
    id: 'gpt-3.5-0301',
    provider: 'openai',
    model: 'GPT-3.5 (0301)',
    inputPrice: 1.5,
    outputPrice: 2.0,
    contextWindow: 4_096,
  },
  {
    id: 'gpt-3.5-turbo-instruct',
    provider: 'openai',
    model: 'GPT-3.5 Turbo Instruct',
    inputPrice: 1.5,
    outputPrice: 2.0,
    contextWindow: 4_096,
  },
  {
    id: 'gpt-3.5-turbo-16k-0613',
    provider: 'openai',
    model: 'GPT-3.5 Turbo 16K (0613)',
    inputPrice: 3.0,
    outputPrice: 4.0,
    contextWindow: 16_385,
  },
  {
    id: 'davinci-002',
    provider: 'openai',
    model: 'davinci-002',
    inputPrice: 2.0,
    outputPrice: 2.0,
    contextWindow: 16_384,
  },
  {
    id: 'babbage-002',
    provider: 'openai',
    model: 'babbage-002',
    inputPrice: 0.4,
    outputPrice: 0.4,
    contextWindow: 16_384,
  },

  // OpenAI — Image generation（https://developers.openai.com/api/docs/pricing）
  {
    id: 'gpt-image-1.5-image',
    provider: 'openai',
    model: 'gpt-image-1.5（Image）',
    inputPrice: 8.0,
    cachedInputPrice: 2.0,
    outputPrice: 32.0,
    contextWindow: 0,
    notes:
      '画像生成。枚単価は画像生成ガイドの Calculating costs を参照（公式）',
  },
  {
    id: 'gpt-image-1.5-text',
    provider: 'openai',
    model: 'gpt-image-1.5（Text）',
    inputPrice: 5.0,
    cachedInputPrice: 1.25,
    outputPrice: 10.0,
    contextWindow: 0,
    notes: '画像生成フロー内の Text modality。枚単価は画像生成ガイドを参照',
  },
  {
    id: 'gpt-image-1-mini-image',
    provider: 'openai',
    model: 'gpt-image-1-mini（Image）',
    inputPrice: 2.5,
    cachedInputPrice: 0.25,
    outputPrice: 8.0,
    contextWindow: 0,
    notes:
      '画像生成。枚単価は画像生成ガイドの Calculating costs を参照（公式）',
  },
  {
    id: 'gpt-image-1-mini-text',
    provider: 'openai',
    model: 'gpt-image-1-mini（Text）',
    inputPrice: 2.0,
    cachedInputPrice: 0.2,
    contextWindow: 0,
    notes: 'Text modality。Output は公式価格表で「—」（要公式確認）',
  },
  {
    id: 'gpt-image-1.5-image-batch',
    provider: 'openai',
    model: 'gpt-image-1.5（Image・Batch）',
    inputPrice: 4.0,
    cachedInputPrice: 1.0,
    outputPrice: 16.0,
    contextWindow: 0,
    notes: 'Batch API。枚単価は画像生成ガイドを参照',
  },
  {
    id: 'gpt-image-1.5-text-batch',
    provider: 'openai',
    model: 'gpt-image-1.5（Text・Batch）',
    inputPrice: 2.5,
    cachedInputPrice: 0.63,
    outputPrice: 5.0,
    contextWindow: 0,
    notes: 'Batch API / Text modality',
  },
  {
    id: 'gpt-image-1-mini-image-batch',
    provider: 'openai',
    model: 'gpt-image-1-mini（Image・Batch）',
    inputPrice: 1.25,
    cachedInputPrice: 0.13,
    outputPrice: 4.0,
    contextWindow: 0,
    notes: 'Batch API。枚単価は画像生成ガイドを参照',
  },
  {
    id: 'gpt-image-1-mini-text-batch',
    provider: 'openai',
    model: 'gpt-image-1-mini（Text・Batch）',
    inputPrice: 1.0,
    cachedInputPrice: 0.1,
    contextWindow: 0,
    notes: 'Batch / Text modality。Output は公式表で「—」',
  },

  // Anthropic
  {
    id: 'claude-opus-4',
    provider: 'anthropic',
    model: 'Claude Opus 4',
    inputPrice: 15.0,
    outputPrice: 75.0,
    contextWindow: 200_000,
  },
  {
    id: 'claude-sonnet-4',
    provider: 'anthropic',
    model: 'Claude Sonnet 4',
    inputPrice: 3.0,
    outputPrice: 15.0,
    contextWindow: 200_000,
  },
  {
    id: 'claude-haiku-3.5',
    provider: 'anthropic',
    model: 'Claude Haiku 3.5',
    inputPrice: 0.8,
    outputPrice: 4.0,
    contextWindow: 200_000,
  },

  // Google (Vertex AI)
  {
    id: 'gemini-2.5-pro',
    provider: 'google',
    model: 'Gemini 2.5 Pro',
    inputPrice: 1.25,
    outputPrice: 10.0,
    longContextInputPrice: 2.5,
    longContextOutputPrice: 15.0,
    contextWindow: 1_000_000,
    notes: '>200K tokens で長文料金適用',
  },
  {
    id: 'gemini-2.5-flash',
    provider: 'google',
    model: 'Gemini 2.5 Flash',
    inputPrice: 0.15,
    outputPrice: 0.6,
    longContextInputPrice: 0.6,
    longContextOutputPrice: 2.4,
    contextWindow: 1_000_000,
    notes: '>200K tokens で長文料金適用',
  },
  {
    id: 'gemini-2.0-flash',
    provider: 'google',
    model: 'Gemini 2.0 Flash',
    inputPrice: 0.1,
    outputPrice: 0.4,
    contextWindow: 1_000_000,
  },
  {
    id: 'gemini-2.0-flash-lite',
    provider: 'google',
    model: 'Gemini 2.0 Flash Lite',
    inputPrice: 0.075,
    outputPrice: 0.3,
    contextWindow: 1_000_000,
  },
];
